version: '3.7'
services:
  web:
    build:
      context: ./
      args:
        configuration: ""
    image: guff-dev:1
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - source: oauth
        target: oauth.json
      - source: session-key
        target: session-key
      - source: postgres-guff-password
        target: postgres-guff-password
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: guff
      PGSSLMODE: disable
  backend-test:
    build:
      context: ./
      target: backend-test
      args:
        configuration: ""
    links:
      - db-test
    depends_on:
      - db-test
    environment:
      PGHOST: db-test
      PGPORT: 5432
      PGUSER: postgres
      PGSSLMODE: disable
  web-test:
    build:
      context: ./
      target: web-test
      args:
        configuration: ""
  db-test:
    image: postgres:11
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: guff_test
  db:
    image: postgres:11
    restart: always
    secrets:
      - source: postgres-guff-password
        target: postgres-guff-password
    expose:
      - 5432
    ports:
      - "55432:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-guff-password
      POSTGRES_USER: guff
      POSTGRES_DB: guff_dev
secrets:
  oauth:
    file: ./.secrets/oauth2-secret-dev.json
  session-key:
    file: ./.secrets/session-key-secret-dev
  postgres-guff-password:
    file: ./.secrets/postgres-guff-password

