version: '3.7'
services:
  web:
    build:
      context: ./
      args:
        configuration: ""
    image: guff-dev:1
    ports:
      - "8080:8080"
    links:
      - db
    secrets:
      - source: oauth
        target: oauth.json
      - source: session-key
        target: session-key
      - source: postgres-guff-password
        target: postgres-guff-password
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: guff
      PGSSLMODE: disable
  db:
    image: postgres:11
    restart: always
    secrets:
      - source: postgres-password
        target: postgres-password
    expose:
      - 5432
    ports:
      - "55432:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
secrets:
  oauth:
    file: ./.secrets/oauth2-secret-dev.json
  session-key:
    file: ./.secrets/session-key-secret-dev
  postgres-password:
    file: ./.secrets/postgres-password
  postgres-guff-password:
    file: ./.secrets/postgres-guff-password

